application: travelplan
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  static_files: index.html
  upload: index.html

- url: /themes
  static_dir: themes

- url: /js
  static_dir: js
  
- url: /langs
  static_dir: langs  

skip_files:
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*
- ^app\.yaml$
