application: carpoolapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /themes
  static_dir: themes

- url: /js
  static_dir: js
  
- url: /langs
  static_dir: langs

- url: /.*
  script: main.py

skip_files:
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*
- ^app\.yaml$
